# Generated by Django 3.1.4 on 2020-12-16 04:08


import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import model_utils.fields

import json.decoder
import uuid

import h1st.django.util.git
import h1st.django.util.pip


class Migration(migrations.Migration):
    initial = True

    dependencies = ('H1stModel', '0001_initial'),

    operations = [
        migrations.CreateModel(
            name='Decision',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    help_text='UUID',
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('input_data',
                 models.JSONField(
                    blank=True,
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Input Data into Decision',
                    null=True,
                    verbose_name='Input Data into Decision')),

                ('model',
                 models.ForeignKey(
                    default=None,
                    help_text='Model producing Decision',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='decisions',
                    related_query_name='decision',
                    to='H1stModel.model',
                    verbose_name='Model producing Decision')),

                ('model_code',
                 models.JSONField(
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Code of Model(s) producing Decision',
                    verbose_name='Code of Model(s) producing Decision')),

                ('git_repo_head_commit_hash',
                 models.CharField(
                    blank=True,
                    db_index=True,
                    default=h1st.django.util.git.get_git_repo_head_commit_hash,
                    help_text='Git Repository Head Commit Hash',
                    max_length=40,
                    null=True,
                    verbose_name='Git Repository Head Commit Hash')),

                ('python_dependencies',
                 models.JSONField(
                    decoder=json.decoder.JSONDecoder,
                    default=h1st.django.util.pip.get_python_dependencies,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Python Dependencies',
                    verbose_name='Python Dependencies')),

                ('output_data',
                 models.JSONField(
                    blank=True,
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Output Data from Decision',
                    null=True,
                    verbose_name='Output Data from Decision')),

                ('created',
                 model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now,
                    editable=False,
                    verbose_name='created')),
                ('modified',
                 model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now,
                    editable=False,
                    verbose_name='modified'))
            ],

            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
                'db_table': 'H1stTrust_Decision',
                'ordering': ('-modified',),
                'permissions': (),
                'get_latest_by': 'modified',
                'abstract': False,
                'managed': True,
                'proxy': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'select_on_save': False,
                'default_related_name': 'decisions',
                'required_db_features': (),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects'
            }
        ),

        migrations.CreateModel(
            name='ModelEvalMetricsSet',

            fields=[
                ('uuid',
                 models.UUIDField(
                    db_index=True,
                    default=uuid.uuid4,
                    editable=False,
                    help_text='UUID',
                    primary_key=True,
                    serialize=False,
                    unique=True,
                    verbose_name='UUID')),

                ('model',
                 models.ForeignKey(
                    default=None,
                    help_text='Model evaluated',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='model_eval_metrics_sets',
                    related_query_name='model_eval_metrics_set',
                    to='H1stModel.model',
                    verbose_name='Model evaluated')),

                ('eval_data',
                 models.JSONField(
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Data for Evaluation',
                    verbose_name='Data for Evaluation')),

                ('eval_metrics',
                 models.JSONField(
                    decoder=json.decoder.JSONDecoder,
                    default=None,
                    encoder=django.core.serializers.json.DjangoJSONEncoder,
                    help_text='Evaluation Metrics',
                    verbose_name='Evaluation Metrics')),

                ('created',
                 model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now,
                    editable=False,
                    verbose_name='created')),
                ('modified',
                 model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now,
                    editable=False,
                    verbose_name='modified'))
            ],

            options={
                'verbose_name': 'Model Evaluation Metrics Set',
                'verbose_name_plural': 'Model Evaluation Metrics Sets',
                'db_table': 'H1stTrust_ModelEvalMetricsSet',
                'ordering': ('-model__modified', '-modified'),
                'permissions': (),
                'get_latest_by': 'modified',
                'abstract': False,
                'managed': True,
                'proxy': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'select_on_save': False,
                'default_related_name': 'model_eval_metrics_sets',
                'required_db_features': (),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects'
            }
        )
    ]
