# Generated by Django 3.2 on 2021-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Model Name', max_length=20)),
                ('description', models.CharField(help_text='Enter Model Description', max_length=255)),
                ('model_input', models.CharField(help_text='Input in Json form', max_length=255)),
                ('model_output', models.CharField(help_text='Output in Json form', max_length=255)),
                ('file_name', models.CharField(max_length=200)),
                ('creator', models.CharField(help_text='Creator', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
