# Generated by Django 3.2 on 2021-05-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='type',
            field=models.CharField(choices=[('TF', 'Tensorflow'), ('PT', 'PyTorch')], default='TF', max_length=2),
        ),
    ]
