# Generated by Django 3.2 on 2021-05-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TF', 'Tensorflow'), ('PT', 'PyTorch')], default='TF', max_length=2)),
                ('name', models.CharField(help_text='Enter Model Name', max_length=20)),
                ('description', models.CharField(help_text='Enter Model Description', max_length=255)),
                ('input', models.JSONField()),
                ('output', models.JSONField()),
                ('output_config', models.JSONField()),
                ('file_name', models.CharField(max_length=200)),
                ('creator', models.CharField(help_text='Creator', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
