# Generated by Django 3.2 on 2021-05-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1st_api', '0004_alter_aimodel_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='creator',
            field=models.CharField(help_text='Creator', max_length=255),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(help_text='Enter Model Name', max_length=255),
        ),
    ]
