# Generated by Django 3.2 on 2021-05-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1st_api', '0006_aimodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='creator',
            field=models.CharField(db_index=True, help_text='Creator', max_length=255),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_id',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
