# Generated by Django 3.1.7 on 2021-03-24 07:55


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = ('H1stModel', '0002_workflow'),

    operations = \
        migrations.AlterModelOptions(
            name='workflow',
            options={
                'base_manager_name': 'objects',
                'default_related_name': 'h1st_workflows',
                'verbose_name': 'H1st Workflow',
                'verbose_name_plural': 'H1st Workflows'
            }
        ),
