# Generated by Django 3.1.7 on 2021-03-24 08:10


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('H1stModel', '0003_workflow_meta'),

    operations = \
        migrations.CreateModel(
            name='MLModel',

            fields=[
                ('model_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='h1st_ml_models',
                    serialize=False,
                    to='H1stModel.model')),

                ('artifact',
                 models.BinaryField(
                    default=None,
                    help_text='Model Artifact (raw binary data)',
                    verbose_name='Model Artifact (raw binary data)'))
            ],

            options={
                'verbose_name': 'H1st ML Model',
                'verbose_name_plural': 'H1st ML Models',
                'db_table': 'H1stModel_MLModel',
                'abstract': False,
                'default_related_name': 'h1st_ml_models',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.model',)
        ),
