# Generated by Django 3.1.7 on 2021-03-24 08:27


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('H1stModel', '0004_MLModel'),

    operations = \
        migrations.CreateModel(
            name='SKLModel',

            fields=[
                ('mlmodel_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='h1st_skl_models',
                    serialize=False, to='H1stModel.mlmodel'))
            ],

            options={
                'verbose_name': 'H1st SciKit-Learn Model',
                'verbose_name_plural': 'H1st SciKit-Learn Models',
                'db_table': 'H1stModel_SKLModel',
                'abstract': False,
                'default_related_name': 'h1st_skl_models',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.mlmodel',)
        ),
