# Generated by Django 3.1.7 on 2021-03-31 03:46


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('H1stModel', '0005_SKLModel'),

    operations = [
        migrations.CreateModel(
            name='KerasModel',

            fields=[
                ('mlmodel_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='h1st_keras_models',
                    serialize=False,
                    to='H1stModel.mlmodel'))
            ],

            options={
                'verbose_name': 'H1st Keras Model',
                'verbose_name_plural': 'H1st Keras Models',
                'db_table': 'H1stModel_KerasModel',
                'abstract': False,
                'default_related_name': 'h1st_keras_models',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.mlmodel',)
        ),

        migrations.CreateModel(
            name='TFModel',

            fields=[
                ('mlmodel_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='h1st_tf_models',
                    serialize=False,
                    to='H1stModel.mlmodel'))
            ],

            options={
                'verbose_name': 'H1st TensorFlow Model',
                'verbose_name_plural': 'H1st TensorFlow Models',
                'db_table': 'H1stModel_TFModel',
                'abstract': False,
                'default_related_name': 'h1st_tf_models',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.mlmodel',)
        ),

        migrations.CreateModel(
            name='TorchModel',

            fields=[
                ('mlmodel_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='h1st_torch_models',
                    serialize=False,
                    to='H1stModel.mlmodel'))
            ],

            options={
                'verbose_name': 'H1st Torch Model',
                'verbose_name_plural': 'H1st Torch Models',
                'db_table': 'H1stModel_TorchModel',
                'abstract': False,
                'default_related_name': 'h1st_torch_models',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.mlmodel',)
        )
    ]
