# Generated by Django 3.2 on 2021-05-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h1st_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='output_config',
            new_name='config',
        ),
    ]
