# Generated by Django 3.2 on 2021-05-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1st_api', '0002_rename_output_config_aimodel_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='model_id',
            field=models.CharField(default="None", max_length=200),
        ),
    ]
