# Generated by Django 3.2 on 2021-05-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h1st_api', '0005_auto_20210511_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
