#!/bin/bash
cd /Users/ctn/src/h1st-ai/h1st/examples/REACT

echo '*** Stopping django...'
pkill -f manage.py

echo '*** Stopping react...'
pkill -f react-scripts

echo '*** Stopping nginx...'
nginx -s stop 2>/dev/null

echo '*** READY.'

