#!/bin/bash -
#
# Script to run an H1st project with a web front-end
#

APPNAME=$1
if [ "$APPNAME" = "" ] ; then
	echo "Usage: $0 <app_name>"
	exit 1
fi


TOPDIR=$PWD
APPDIR=$TOPDIR/$APPNAME
echo "*** Working directory: $TOPDIR"
echo "*** Application directory: $APPDIR"

$APPDIR/utils/h1-run-app
