#!/bin/bash
cd /Users/khoama/Workspace/Aitomatic/test-django/examples/model_hosting_1

echo '*** Stopping django...'
pkill -f manage.py

echo '*** Stopping react...'
pkill -f react-scripts

echo '*** Stopping nginx...'
nginx -s stop 2>/dev/null

echo '*** READY.'

