#!/bin/bash
#
# H1st customizations are in:
#   frameworks/django/project/__init__.py
#   frameworks/django/project/__init__.py
#   frameworks/django/project/urls.py
#

# Copy model-io.json files to /tmp
cp *.json /tmp/

# start TensorFlow server
docker run -d -t --rm -p 8501:8501 --name serving -v "$(pwd)/models/:/models/" tensorflow/serving --model_config_file=/models/models.config --model_config_file_poll_wait_seconds=60

python ui/frameworks/django/manage.py runserver
