# Generated by Django 3.1.5 on 2021-01-26 20:11


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = ('H1stData', '0001_initial'),

    operations = \
        migrations.CreateModel(
            name='CSVDataSet',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='csv_data_sets',
                    serialize=False,
                    to='H1stData.dataset')),

                ('path',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Path/URL',
                    max_length=255,
                    verbose_name='Data Set Path/URL')),

                ('is_dir',
                 models.BooleanField(
                    db_index=True,
                    default=False,
                    help_text='Data Set Path/URL is Directory?',
                    verbose_name='Data Set Path/URL is Directory?'))
            ],

            options={
                'verbose_name': 'CSV Data Set',
                'verbose_name_plural': 'CSV Data Sets',
                'db_table': 'H1stData_CSVDataSet',
                'abstract': False,
                'default_related_name': 'csv_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('H1stData.dataset',)
        ), \
        \
        migrations.CreateModel(
            name='NamedCSVDataSet',

            fields=[
                ('csvdataset_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    related_name='named_csv_data_sets',
                    serialize=False,
                    to='H1stData.csvdataset')),

                ('name',
                 models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Data Set Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Data Set Unique Name'))
            ],

            options={
                'verbose_name': 'Named CSV Data Set',
                'verbose_name_plural': 'Named CSV Data Sets',
                'db_table': 'H1stData_NamedCSVDataSet',
                'ordering': ('name',),
                'abstract': False,
                'default_related_name': 'named_csv_data_sets',
                'base_manager_name': 'objects'
            },

            bases=('H1stData.csvdataset',
                   models.Model)
        )
